[package]
name = "antihash"
version = "1.0.0"
authors = ["Alessandro Bortolin <bortolin.alessandro@outlook.it>"]
edition = "2018"

[dependencies]
binary-heap-plus = "^0.2.0"
clap = "^2.33.1"
rand = "^0.7.3"
